/*NAME:VISHAL SHARMA
PURPOSE:TO DEMONSTRATE THE POINTER VARIABLES INITIALIZATION WITH ADDRESS OF ANOTHER VARIABLE*/
#include <stdio.h>  //PREPROSESSIVE DIRECTIVE TO INCLUDE STANDARD INPUT OUTPUT HEADER FILE
int main()		//STARTING OF MAIN PROGRAM
{
   //VARIABLE DECLARATION
   int num = 10;

   //POINTER DECLARATION
   int *p;

   //ASSIGNING THE ADDRESS OF NUM TO THE POINTER "p"
   p = &num;

   printf("Address of variable %d is: %p", num, p);
   return 0;		//RETURN STATEMENT
} 